apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
gke:
  cluster: projects/tasleem-project-trial-project/locations/us-central1-c/clusters/cluster-2
