replicaCount: 1
workloadName: stage-application
image:
  repository: us-central1-docker.pkg.dev/tasleem-project-trial-project/helm-cicd-repo/helm-cicd-image
  tag: latest
  pullPolicy: IfNotPresent
monitoring: false
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 128Mi
service:
  type: LoadBalancer
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80